service: sc-backend

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: ap-southeast-2
  # profile: serverless-admin
  timeout: 20

  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:PutObject
      Resource: "*"
    - Effect: Allow
      Action:
        - dynamodb:UpdateItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.RETAIL_TABLE}"
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.RETAIL_INFO_TABLE}"

  environment:
    SHEET_NAME: RawData
    RETAIL_TABLE: ${self:service}-${self:custom.dynamodb}-${opt:stage, self:provider.stage}
    RETAIL_INFO_TABLE: ${self:service}-${self:custom.dynamodb}-info-${opt:stage, self:provider.stage}
    WEB_URL: https://www.mbie.govt.nz/building-and-energy/energy-and-natural-resources/energy-statistics-and-modelling/energy-statistics/energy-prices/electricity-cost-and-price-monitoring/
    REGEX: qsdep-report-\d{2}-\w{3}-\d{4}.xlsx
    FILE_URL_PREFIX: https://www.mbie.govt.nz/assets/Data-Files/Energy/nz-energy-quarterly-and-energy-in-nz/
    BUCKET: ${self:service}-${self:custom.bucket}-${opt:stage, self:provider.stage}

custom:
  bucket: raw-files
  dynamodb: retailkwh
  pythonRequirements:
    dockerizePip: true

functions:
  parse_xlsx:
    handler: parsefile.parse_xlsx
    package:
      artifact:
    timeout: 600
    events:
      - s3: 
          bucket: ${self:provider.environment.BUCKET}
          event: s3:ObjectCreated:*
          rules:
            - prefix: qsdep-report-
            - suffix: .xlsx
  
  file_scrapper:
    handler: filescrapper.file_scrapper
    package:
      artifact:
resources:
  Resources:
    RetailTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:provider.environment.RETAIL_TABLE}
        AttributeDefinitions:
          - AttributeName: loc_retail
            AttributeType: S
          - AttributeName: date_retail
            AttributeType: S
        KeySchema:
          - AttributeName: loc_retail
            KeyType: HASH
          - AttributeName: date_retail
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
    RetailInfoTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:provider.environment.RETAIL_INFO_TABLE}
        AttributeDefinitions:
          - AttributeName: file_name
            AttributeType: S
        KeySchema:
          - AttributeName: file_name
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

plugins:
  - serverless-python-requirements
